spring:
  application:
    name: live-streaming-im-provier

  redis:
    host: 192.168.64.14
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 10
        max-active: 100
        max-idle: 10

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://192.168.64.14:8848
  protocol:
    name: dubbo
    port: 6069
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500
  consumer:
      timeout: 20000

server:
  port: 8089
